disabled_rules:
- trailing_whitespace

excluded:
- Pods
- vendor

# rule identifiers to opt in
opt_in_rules:
  - closure_spacing
  - force_unwrapping
  - missing_docs
  - empty_count
  - first_where
  - closure_end_indentation
  - explicit_init
  - implicit_return
  - number_separator
  - implicitly_unwrapped_optional

# special configuration for rules
line_length:
  warning: 130
  error: 150
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false

file_length:
  warning: 200
  error: 300

function_parameter_count:
  warning: 5
  error: 8

large_tuple:
  warning: 2
  error: 3

function_body_length:
  warning: 20
  error: 30

cyclomatic_complexity:
  warning: 8
  error: 10
  ignores_case_statements: false

number_separator:
  minimum_length: 0

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

implicitly_unwrapped_optional:
    mode: allExceptIBOutlets


nesting:
  type_level: 3

identifier_name:
  excluded:
    - i
    - j
    - k
